from weasyprint import HTML, CSS
import tempfile
import os
import datetime

def generate_pdf(query, response, doc_type="Legal Opinion", save_dir="./generated_docs"):
    """Generate a PDF document from a query and response."""
    try:
        # Ensure save directory exists
        os.makedirs(save_dir, exist_ok=True)
        
        # Format current date
        current_date = datetime.datetime.now().strftime("%d %B %Y")
        
        # Create HTML content based on document type
        if doc_type == "Legal Opinion":
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>Legal Opinion - ShariaAI</title>
                <style>
                    body {{
                        font-family: 'Noto Sans Arabic', Arial, sans-serif;
                        margin: 2cm;
                        color: #333;
                        line-height: 1.5;
                    }}
                    .header {{
                        text-align: center;
                        color: #0A4D68;
                        margin-bottom: 2cm;
                    }}
                    .logo {{
                        text-align: center;
                        margin-bottom: 1cm;
                    }}
                    .title {{
                        font-size: 24pt;
                        font-weight: bold;
                        margin-bottom: 0.5cm;
                    }}
                    .subtitle {{
                        font-size: 14pt;
                        margin-bottom: 0.5cm;
                    }}
                    .date {{
                        font-size: 12pt;
                        margin-bottom: 1cm;
                    }}
                    .section-title {{
                        font-size: 14pt;
                        font-weight: bold;
                        color: #0A4D68;
                        margin-top: 1cm;
                        margin-bottom: 0.5cm;
                        border-bottom: 1px solid #0A4D68;
                        padding-bottom: 0.2cm;
                    }}
                    .content {{
                        text-align: justify;
                    }}
                    .footer {{
                        text-align: center;
                        font-size: 10pt;
                        color: #666;
                        margin-top: 2cm;
                        border-top: 1px solid #ccc;
                        padding-top: 0.5cm;
                    }}
                    .watermark {{
                        position: fixed;
                        bottom: 2cm;
                        right: 2cm;
                        opacity: 0.1;
                        font-size: 72pt;
                        transform: rotate(-45deg);
                        z-index: -1;
                    }}
                </style>
            </head>
            <body>
                <div class="watermark">ShariaAI</div>
                <div class="header">
                    <div class="logo">⚖️</div>
                    <div class="title">Legal Opinion</div>
                    <div class="subtitle">ShariaAI - Omani Legal Assistant</div>
                    <div class="date">{current_date}</div>
                </div>
                
                <div class="section-title">Legal Inquiry</div>
                <div class="content">
                    {query}
                </div>
                
                <div class="section-title">Legal Opinion</div>
                <div class="content">
                    {response}
                </div>
                
                <div class="section-title">Disclaimer</div>
                <div class="content">
                    This document was generated by an AI legal assistant and is provided for informational purposes only. 
                    It does not constitute legal advice and should not be relied upon as such. Please consult with a qualified 
                    legal professional for advice specific to your situation.
                </div>
                
                <div class="footer">
                    Generated by ShariaAI on {current_date}<br>
                    © 2025 ShariaAI - All Rights Reserved
                </div>
            </body>
            </html>
            """
        elif doc_type == "Certificate":
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>Certificate - ShariaAI</title>
                <style>
                    body {{
                        font-family: 'Noto Sans Arabic', Arial, sans-serif;
                        margin: 1cm;
                        color: #333;
                        line-height: 1.5;
                        border: 20px solid #0A4D68;
                        padding: 2cm;
                        text-align: center;
                    }}
                    .header {{
                        color: #0A4D68;
                        margin-bottom: 2cm;
                    }}
                    .logo {{
                        font-size: 48pt;
                        margin-bottom: 1cm;
                    }}
                    .title {{
                        font-size: 36pt;
                        font-weight: bold;
                        margin-bottom: 1cm;
                    }}
                    .subtitle {{
                        font-size: 18pt;
                        margin-bottom: 2cm;
                    }}
                    .content {{
                        font-size: 14pt;
                        margin-bottom: 2cm;
                    }}
                    .signature {{
                        font-size: 12pt;
                        margin-top: 3cm;
                    }}
                    .date {{
                        font-size: 14pt;
                        margin-top: 1cm;
                    }}
                    .footer {{
                        font-size: 10pt;
                        color: #666;
                        margin-top: 2cm;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="logo">⚖️</div>
                    <div class="title">Certificate</div>
                    <div class="subtitle">ShariaAI - Omani Legal Assistant</div>
                </div>
                
                <div class="content">
                    This is to certify that the following legal inquiry:<br><br>
                    "{query}"<br><br>
                    Has been processed and the following determination has been made:<br><br>
                    {response}
                </div>
                
                <div class="signature">
                    _________________________<br>
                    Issued by ShariaAI
                </div>
                
                <div class="date">
                    {current_date}
                </div>
                
                <div class="footer">
                    This certificate is generated by an AI system and may require validation by a legal professional.
                </div>
            </body>
            </html>
            """
        elif doc_type == "Contract Template":
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>Contract Template - ShariaAI</title>
                <style>
                    body {{
                        font-family: 'Noto Sans Arabic', Arial, sans-serif;
                        margin: 2cm;
                        color: #333;
                        line-height: 1.5;
                    }}
                    .header {{
                        text-align: center;
                        color: #0A4D68;
                        margin-bottom: 2cm;
                    }}
                    .title {{
                        font-size: 24pt;
                        font-weight: bold;
                        margin-bottom: 0.5cm;
                    }}
                    .subtitle {{
                        font-size: 14pt;
                        margin-bottom: 1cm;
                    }}
                    .section {{
                        margin-top: 1cm;
                        margin-bottom: 1cm;
                    }}
                    .section-title {{
                        font-size: 14pt;
                        font-weight: bold;
                        color: #0A4D68;
                        margin-bottom: 0.5cm;
                    }}
                    .content {{
                        text-align: justify;
                    }}
                    .signature {{
                        margin-top: 3cm;
                        display: flex;
                        justify-content: space-between;
                    }}
                    .signature-box {{
                        width: 45%;
                    }}
                    .footer {{
                        text-align: center;
                        font-size: 10pt;
                        color: #666;
                        margin-top: 2cm;
                        border-top: 1px solid #ccc;
                        padding-top: 0.5cm;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="title">Contract Template</div>
                    <div class="subtitle">Based on Omani Legal Framework</div>
                </div>
                
                <div class="section">
                    <div class="section-title">Contract Basis</div>
                    <div class="content">
                        This contract template is based on the inquiry:<br>
                        {query}
                    </div>
                </div>
                
                <div class="section">
                    <div class="section-title">Contract Terms</div>
                    <div class="content">
                        {response}
                    </div>
                </div>
                
                <div class="section">
                    <div class="section-title">Legal Compliance</div>
                    <div class="content">
                        This contract template has been generated in consideration of relevant Omani laws and regulations. 
                        Parties are advised to seek legal counsel before finalizing any agreement based on this template.
                    </div>
                </div>
                
                <div class="signature">
                    <div class="signature-box">
                        <p>Party 1:</p>
                        <p>Name: ________________________</p>
                        <p>Signature: ___________________</p>
                        <p>Date: ________________________</p>
                    </div>
                    <div class="signature-box">
                        <p>Party 2:</p>
                        <p>Name: ________________________</p>
                        <p>Signature: ___________________</p>
                        <p>Date: ________________________</p>
                    </div>
                </div>
                
                <div class="footer">
                    Generated by ShariaAI on {current_date}<br>
                    This is a template only and should be reviewed by a qualified legal professional before use.
                </div>
            </body>
            </html>
            """
        else:  # Legal Summary
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>Legal Summary - ShariaAI</title>
                <style>
                    body {{
                        font-family: 'Noto Sans Arabic', Arial, sans-serif;
                        margin: 2cm;
                        color: #333;
                        line-height: 1.5;
                    }}
                    .header {{
                        text-align: center;
                        color: #0A4D68;
                        margin-bottom: 2cm;
                    }}
                    .title {{
                        font-size: 24pt;
                        font-weight: bold;
                        margin-bottom: 0.5cm;
                    }}
                    .subtitle {{
                        font-size: 14pt;
                        margin-bottom: 0.5cm;
                    }}
                    .date {{
                        font-size: 12pt;
                        margin-bottom: 1cm;
                    }}
                    .section-title {{
                        font-size: 14pt;
                        font-weight: bold;
                        color: #0A4D68;
                        margin-top: 1cm;
                        margin-bottom: 0.5cm;
                    }}
                    .content {{
                        text-align: justify;
                    }}
                    .footer {{
                        text-align: center;
                        font-size: 10pt;
                        color: #666;
                        margin-top: 2cm;
                        border-top: 1px solid #ccc;
                        padding-top: 0.5cm;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="title">Legal Summary</div>
                    <div class="subtitle">ShariaAI - Omani Legal Assistant</div>
                    <div class="date">{current_date}</div>
                </div>
                
                <div class="section-title">Query</div>
                <div class="content">
                    {query}
                </div>
                
                <div class="section-title">Summary</div>
                <div class="content">
                    {response}
                </div>
                
                <div class="section-title">Note</div>
                <div class="content">
                    This summary is based on the Omani legal framework as understood by ShariaAI. 
                    For comprehensive legal advice, please consult with a qualified legal professional.
                </div>
                
                <div class="footer">
                    Generated by ShariaAI on {current_date}<br>
                    © 2025 ShariaAI - All Rights Reserved
                </div>
            </body>
            </html>
            """
        
        # Create a temporary HTML file
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as temp_html:
            temp_html.write(html_content.encode('utf-8'))
            temp_html_path = temp_html.name
        
        # Generate PDF file name
        pdf_filename = f"{doc_type.replace(' ', '_').lower()}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        pdf_path = os.path.join(save_dir, pdf_filename)
        
        # Generate PDF from HTML
        HTML(temp_html_path).write_pdf(pdf_path)
        
        # Clean up temporary HTML file
        os.unlink(temp_html_path)
        
        return pdf_path
    
    except Exception as e:
        raise Exception(f"Error generating PDF: {str(e)}")

def create_custom_report(title, sections, doc_type=None, client_name=None, save_dir="./generated_docs"):
    """Create a custom report with specified sections."""
    try:
        # Ensure save directory exists
        os.makedirs(save_dir, exist_ok=True)
        
        # Format current date
        current_date = datetime.datetime.now().strftime("%d %B %Y")
        
        # Start HTML content
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{title} - ShariaAI</title>
            <style>
                body {{
                    font-family: 'Noto Sans Arabic', Arial, sans-serif;
                    margin: 2cm;
                    color: #333;
                    line-height: 1.5;
                }}
                .header {{
                    text-align: center;
                    color: #0A4D68;
                    margin-bottom: 2cm;
                }}
                .logo {{
                    text-align: center;
                    margin-bottom: 1cm;
                }}
                .title {{
                    font-size: 24pt;
                    font-weight: bold;
                    margin-bottom: 0.5cm;
                }}
                .date {{
                    font-size: 12pt;
                    margin-bottom: 1cm;
                }}
                .section-title {{
                    font-size: 14pt;
                    font-weight: bold;
                    color: #0A4D68;
                    margin-top: 1cm;
                    margin-bottom: 0.5cm;
                    border-bottom: 1px solid #0A4D68;
                    padding-bottom: 0.2cm;
                }}
                .content {{
                    text-align: justify;
                }}
                .footer {{
                    text-align: center;
                    font-size: 10pt;
                    color: #666;
                    margin-top: 2cm;
                    border-top: 1px solid #ccc;
                    padding-top: 0.5cm;
                }}
                .watermark {{
                    position: fixed;
                    bottom: 2cm;
                    right: 2cm;
                    opacity: 0.1;
                    font-size: 72pt;
                    transform: rotate(-45deg);
                    z-index: -1;
                }}
            </style>
        </head>
        <body>
            <div class="watermark">ShariaAI</div>
            <div class="header">
                <div class="logo">⚖️</div>
                <div class="title">{title}</div>
                <div class="date">{current_date}</div>
            </div>
        """
        
        # Add sections
        for section in sections:
            section_title = section.get("title", "")
            section_content = section.get("content", "")
            
            html_content += f"""
            <div class="section-title">{section_title}</div>
            <div class="content">
                {section_content}
            </div>
            """
        
        # Add footer
        html_content += f"""
            <div class="footer">
                Generated by ShariaAI on {current_date}<br>
                © 2025 ShariaAI - All Rights Reserved
            </div>
        </body>
        </html>
        """
        
        # Create a temporary HTML file
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as temp_html:
            temp_html.write(html_content.encode('utf-8'))
            temp_html_path = temp_html.name
        
        # Generate PDF file name
        pdf_filename = f"{title.replace(' ', '_').lower()}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        pdf_path = os.path.join(save_dir, pdf_filename)
        
        # Generate PDF from HTML
        HTML(temp_html_path).write_pdf(pdf_path)
        
        # Clean up temporary HTML file
        os.unlink(temp_html_path)
        
        return pdf_path
    
    except Exception as e:
        raise Exception(f"Error creating custom report: {str(e)}")
